name: Rune-Core
main: com.dank1234.plugin.Main
version: 0.1-DEVELOPMENT
database: true
load: POSTWORLD
api-version: 1.20

depend:
#  - LuckPerms

libraries:
  - io.papermc.paper:paper-api:1.21.3-R0.1-SNAPSHOT
  - org.yaml:snakeyaml:2.0
  - org.reflections:reflections:0.9.12
  - org.jetbrains:annotations:24.1.0
  - org.mariadb.jdbc:mariadb-java-client:3.4.1
  - com.zaxxer:HikariCP:5.1.0
  - org.graalvm.sdk:graal-sdk:22.3.0
  - org.graalvm.js:js:22.3.0
  - org.jetbrains.kotlin:kotlin-stdlib:2.1.0
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.0
  - org.jetbrains.kotlin:kotlin-scripting-jvm:2.1.0
  - org.jetbrains.kotlin:kotlin-scripting-jvm-host:2.1.0
  - org.jetbrains.kotlin:kotlin-scripting-common:2.1.0
  - org.jetbrains.kotlin:kotlin-script-runtime:2.1.0
  - org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:2.1.0
  - org.jetbrains.kotlin:kotlin-reflect:2.1.0
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0
  - org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.20.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.20.0

