name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Rune-Core
          path: target/Rune-Core-v0.0.1.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Rune-Core
          path: ./plugin

      - name: Deploy to other PC
        run: scp -o StrictHostKeyChecking=no ./plugin/*.jar 'Daniel Kenyon'@'192.168.0.189':F:/plugins/RuneCore.jar
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}