name: Deploy Plugin to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the plugin
        run: mvn package

      - name: Deploy to Minecraft Server
        env:
          SERVER_IP: 81.101.214.225
          SERVER_USER: ftpuser
          SERVER_PASSWORD: B24Z69K11M.

        run: |
          # Upload plugin to HUB
          curl --ftp-pasv -T target/Rune-Core-0.0.1.jar ftp://$SERVER_USER:$SERVER_PASSWORD@$SERVER_IP:/opt/mcsmanager/daemon/data/InstanceData/1c268d784f574099a622f9feb387a8c1/plugins/

          # Upload plugin to PROXY
          curl --ftp-pasv -T target/Rune-Core-0.0.1 ftp://$SERVER_USER:$SERVER_PASSWORD@$SERVER_IP:/opt/mcsmanager/daemon/data/InstanceData/eb73ef88e2134da084b04980448ed0a9/plugins/

          # Upload plugin to SURVIVAL
          curl --ftp-pasv -T target/Rune-Core-0.0.1 ftp://$SERVER_USER:$SERVER_PASSWORD@$SERVER_IP:/opt/mcsmanager/daemon/data/InstanceData/2091a8f892c3422caa0758e423138a18/plugins/

          # Upload plugin to SKYBLOCK
          curl --ftp-pasv -T target/Rune-Core-0.0.1 ftp://$SERVER_USER:$SERVER_PASSWORD@$SERVER_IP:/opt/mcsmanager/daemon/data/InstanceData/d02ff1361b114c4280fc0ffb06f6f934/plugins/