name: Deploy Plugin to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build the plugin
        run: ./mvn package

      - name: Deploy to Minecraft Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          scp build/libs/your-plugin.jar $SERVER_USER@$SERVER_IP:/path/to/server/plugins/
          ssh $SERVER_USER@$SERVER_IP "systemctl restart minecraft" # Optional: restart server to load plugin